### ISSUE TITLE
Syntax highlighting?

### ISSUE THREAD

**Issue by FreedomBen** [jonklein/niex#4]
Dude, freaking amazing work.  I just tried this out and it may revolutionize how I develop/test my apps.  Really awesome.

Any plans to add syntax highlighting to the output, much like iEX does?  That would be killer.

I can't do it right now but would send a PR for it later if somebody doesn't beat me to it.  Thanks for this amazing tool and for making it so easy to drop into my existing Phoenix app so I can use it to test my code!

**Comment by FreedomBen** [comment]
I'm leaving some notes here for either myself in the future or someone else who decides to do it:

highlight.js looks like it should be pretty easy to drop in and it's used by stack exchange among others.  The Elixir support looks really crappy though:  https://highlightjs.org/usage/

Github uses Linguist, which seems worth looking at too:  https://github.com/github/linguist

**Comment by jonklein** [comment]
Great suggestion, and thanks for the links to possible tools.  I'll need to do some investigation of the various options to figure out how to proceed.

**Comment by jonklein** [comment]
A quick look at [PrismJS](https://prismjs.com) looks promising.

**Comment by jonklein** [comment]
<img width="796" alt="Screen Shot 2020-12-30 at 8 08 50 PM" src="https://user-images.githubusercontent.com/194568/103389136-ff363280-4ada-11eb-89d9-16f7d75ae61b.png">

**Comment by jonklein** [comment]
https://github.com/jonklein/niex/tree/feature/highlight if you'd like to try it out

**Comment by FreedomBen** [comment]
Awesome, it's working great on mine, thank you!

**Comment by jonklein** [comment]
Now live in master.
