### ISSUE TITLE
State should not start out dirty on the default new project, which prompts the user to save before loading

### ISSUE THREAD

**Issue by FreedomBen** [jonklein/niex#5]
When you start with the Untitled Notebook that just has `IO.inspect("hello, world")` you often want to load a previous notebook.  In that case you hit the "OPEN" button and you are asked if you want to proceed with unsaved changes.  Given that it's the default and I doubt anybody really wants to save it, IMHO it should not ask.  Making the state not start out dirty seems like the right fix.

(I can also look at this when I have time if nobody else does it first)

**Comment by jonklein** [comment]
Good point - will update.

**Comment by jonklein** [comment]
Fixed in master.
