### ISSUE TITLE
Every Code Results in ** (ArgumentError) argument error    (stdlib 3.14) :ets.member(Mix.Compilers.ApplicationTracer, Enum)

### ISSUE THREAD

**Issue by gallexme** [jonklein/niex#7]
Erlang/OTP 23 [erts-11.1.4] [source] [64-bit] [smp:24:24] [ds:24:24:10] [async-threads:1] [hipe]
![image](https://user-images.githubusercontent.com/1122989/103463448-be355c80-4d2c-11eb-86bc-e7bbb992bbfa.png)

running inside an Umbrella application if that helps

**Comment by gallexme** [comment]
https://github.com/elixir-lang/elixir/issues/10466#issue-733126264


manually updating elixir to above 1.11 worked

**Comment by jonklein** [comment]
Though your upgrade may have resolved it, I think there's a real issue here with the default __ENV__ value being captured from the compile time - should be resolved in the commit above.
